"""Build the static GitHub Pages site from each design's design.toml and Markdown.

  build_site.py                 build the site into .work/site
  build_site.py --write-readme  also rewrite the design table in README.md
  build_site.py --check         build, then verify links, README table and vendored files
"""

import argparse
from dataclasses import dataclass
import datetime
from html import escape
from html.parser import HTMLParser
import json
from pathlib import Path, PurePosixPath
import posixpath
import shutil
import sys
import tomllib
from urllib.parse import urlsplit

import markdown_subset
import vendor_three


ROOT = Path(__file__).resolve().parents[1]
SITE_SOURCE = ROOT / "site"
DEFAULT_OUT = ROOT / ".work/site"
REPOSITORY_URL = "https://github.com/sabas0ba/printables"
SITE_URL = "https://sabas0ba.github.io/printables/"
SITE_TITLE = "printables"
SITE_DESCRIPTION = "3D-printable designs with their CAD sources, previews and STL files."
PUBLISHED_SUFFIXES = {".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".stl"}
README_START = "<!-- designs:start (generated by scripts/build_site.py) -->"
README_END = "<!-- designs:end -->"


class SiteError(Exception):
    pass


@dataclass(frozen=True)
class Part:
    file: str
    quantity: int
    description: str


@dataclass(frozen=True)
class Design:
    slug: str
    title: str
    summary: str
    prototype: bool
    added: datetime.date
    lang: str
    source: str
    cover: str
    pages: tuple[str, ...]
    parts: tuple[Part, ...]

    @property
    def printed_parts(self) -> int:
        return sum(part.quantity for part in self.parts)

    @property
    def printed_files(self) -> int:
        return sum(1 for part in self.parts if part.quantity > 0)


def load_design(directory: Path) -> Design:
    path = directory / "design.toml"
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    try:
        parts = tuple(Part(p["file"], int(p["quantity"]), p["description"])
                      for p in data["parts"])
        design = Design(
            slug=directory.name, title=data["title"], summary=data["summary"],
            prototype=bool(data["prototype"]), added=data["added"], lang=data["lang"],
            source=data["source"], cover=data["cover"], pages=tuple(data.get("pages", ())),
            parts=parts)
    except KeyError as error:
        raise SiteError(f"{path.relative_to(directory.parent)}: missing key {error}") from error
    if not isinstance(design.added, datetime.date):
        raise SiteError(f"{path.relative_to(directory.parent)}: 'added' must be a TOML date")
    for name in [design.cover, "README.md", *design.pages, *(p.file for p in parts)]:
        if not (directory / name).is_file():
            raise SiteError(f"{path.relative_to(directory.parent)}: file not found: {name}")
    if any(part.quantity < 0 for part in parts):
        raise SiteError(f"{path.relative_to(directory.parent)}: negative quantity")
    return design


def load_designs(root: Path = ROOT) -> list[Design]:
    designs = [load_design(path.parent) for path in root.glob("*/design.toml")]
    return sorted(designs, key=lambda d: (d.added, d.slug), reverse=True)


# Markdown rendering ----------------------------------------------------------

def output_name(doc: str) -> str:
    """Map a Markdown file inside a design to its HTML page path."""
    path = PurePosixPath(doc)
    return "index.html" if path.name == "README.md" else str(path.with_suffix(".html"))


def is_relative_url(url: str) -> bool:
    parts = urlsplit(url)
    return not (parts.scheme or parts.netloc or url.startswith(("#", "/")))


@dataclass
class LinkContext:
    """Rewrites relative links of one Markdown page in one design directory."""
    root: Path
    slug: str
    doc: str
    pages: frozenset[str]
    published: set[str]

    def rewrite(self, url: str) -> str:
        if not is_relative_url(url):
            return url
        parts = urlsplit(url)
        fragment = f"#{parts.fragment}" if parts.fragment else ""
        doc_dir = posixpath.dirname(self.doc)
        repo_path = posixpath.normpath(posixpath.join(self.slug, doc_dir, parts.path))
        page_dir = posixpath.join(self.slug, posixpath.dirname(output_name(self.doc)))
        if repo_path.startswith("../"):
            raise SiteError(f"{self.slug}/{self.doc}: link leaves the repository: {url}")
        if not (self.root / repo_path).exists():
            raise SiteError(f"{self.slug}/{self.doc}: broken link: {url}")
        if repo_path == "README.md":
            return posixpath.relpath("index.html", page_dir) + fragment
        inside = repo_path.startswith(self.slug + "/")
        local = repo_path.removeprefix(self.slug + "/")
        if inside and (local in self.pages or local == "README.md"):
            return posixpath.relpath(posixpath.join(self.slug, output_name(local)),
                                     page_dir) + fragment
        if inside and PurePosixPath(local).suffix.lower() in PUBLISHED_SUFFIXES:
            self.published.add(local)
            return posixpath.relpath(repo_path, page_dir) + fragment
        kind = "tree" if (self.root / repo_path).is_dir() else "blob"
        return f"{REPOSITORY_URL}/{kind}/main/{repo_path}{fragment}"


def render_markdown(text: str, context: LinkContext, drop_title: bool) -> str:
    try:
        return markdown_subset.render(text, context.rewrite, drop_title,
                                      name=f"{context.slug}/{context.doc}")
    except markdown_subset.MarkdownError as error:
        raise SiteError(str(error)) from error


def markdown_title(text: str, fallback: str) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return fallback


# HTML templates --------------------------------------------------------------

def layout(title: str, body: str, depth: int, head: str = "",
           description: str = SITE_DESCRIPTION) -> str:
    base = "../" * depth
    full_title = SITE_TITLE if title == SITE_TITLE else f"{title} | {SITE_TITLE}"
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(full_title)}</title>
<meta name="description" content="{escape(description)}">
<link rel="stylesheet" href="{base}assets/style.css">
{head}</head>
<body>
<header class="site-header"><div class="wrap">
<a class="site-name" href="{base}index.html">{escape(SITE_TITLE)}</a>
<a class="site-repo" href="{REPOSITORY_URL}">Source on GitHub</a>
</div></header>
<main class="wrap">
{body}
</main>
<footer class="site-footer"><div class="wrap">
Unless otherwise noted, the designs are licensed under
<a href="{REPOSITORY_URL}/blob/main/LICENSE.md">CC BY-SA 4.0</a>.
The 3D viewer uses <a href="https://threejs.org/">three.js</a> (MIT).
</div></footer>
</body>
</html>
"""


def badges(design: Design) -> str:
    items = ['<span class="badge badge-prototype">Prototype</span>'] if design.prototype else []
    items.append(f'<span class="badge">{escape(design.source)}</span>')
    return " ".join(items)


def plural(count: int, noun: str) -> str:
    return f"{count} {noun}" if count == 1 else f"{count} {noun}s"


def parts_summary(design: Design) -> str:
    return (f"{plural(design.printed_parts, 'printed part')} from "
            f"{plural(design.printed_files, 'STL file')}")


def index_page(designs: list[Design]) -> str:
    cards = []
    for design in designs:
        href = f"{design.slug}/index.html"
        cards.append(f"""<li><a class="card" href="{escape(href)}">
<img src="{escape(f'{design.slug}/{design.cover}')}" alt="" loading="lazy">
<div class="card-body">
<h2>{escape(design.title)}</h2>
<p>{escape(design.summary)}</p>
<p class="meta">{badges(design)} <span>{escape(parts_summary(design))}</span></p>
</div></a></li>""")
    body = f"""<section class="intro">
<h1>{escape(SITE_TITLE)}</h1>
<p>{escape(SITE_DESCRIPTION)} Each design page has an interactive 3D view of the STL files,
the parts list with download links, and the full design notes.</p>
</section>
<ul class="cards">
{chr(10).join(cards)}
</ul>"""
    return layout(SITE_TITLE, body, depth=0)


def format_size(size: int) -> str:
    return f"{size / 1024:.0f} KiB" if size < 1024 * 1024 else f"{size / 1048576:.1f} MiB"


def design_page(design: Design, readme_html: str, root: Path) -> str:
    rows, buttons = [], []
    for index, part in enumerate(design.parts):
        size = (root / design.slug / part.file).stat().st_size
        quantity = str(part.quantity) if part.quantity else "–"
        name = PurePosixPath(part.file).name
        rows.append(f"""<tr><td><a href="{escape(part.file)}" download>{escape(name)}</a></td>
<td class="num">{quantity}</td><td>{escape(part.description)}</td>
<td class="num">{format_size(size)}</td></tr>""")
        pressed = "true" if index == 0 else "false"
        buttons.append(f'<button type="button" data-stl="{escape(part.file)}" '
                       f'aria-pressed="{pressed}">{escape(name)}</button>')
    importmap = json.dumps({"imports": {
        "three": "../assets/vendor/three/three.module.js",
        "three/addons/": "../assets/vendor/three/addons/"}})
    head = (f'<script type="importmap">{importmap}</script>\n'
            '<script type="module" src="../assets/viewer.js"></script>\n')
    source_url = f"{REPOSITORY_URL}/tree/main/{design.slug}"
    body = f"""<nav class="crumbs"><a href="../index.html">{escape(SITE_TITLE)}</a> /</nav>
<header class="design-head">
<h1>{escape(design.title)}</h1>
<p class="summary">{escape(design.summary)}</p>
<p class="meta">{badges(design)} <span>{escape(parts_summary(design))}</span>
<a href="{escape(source_url)}">Source files</a></p>
</header>
<section class="viewer" data-viewer aria-label="3D view of the STL files">
<div class="viewer-stage">
<img class="viewer-poster" src="{escape(design.cover)}" alt="Preview of {escape(design.title)}">
<button type="button" class="viewer-start">Open 3D view</button>
</div>
<div class="viewer-parts" role="group" aria-label="Part shown in the 3D view">
{chr(10).join(buttons)}
</div>
<p class="viewer-info" aria-live="polite">Drag to rotate, scroll or pinch to zoom,
right-drag or two-finger drag to pan. Units: mm.</p>
<noscript><p>The 3D view requires JavaScript; the preview images and STL files remain available.</p></noscript>
</section>
<section class="parts">
<h2>Files</h2>
<table class="table">
<thead><tr><th>STL</th><th class="num">Qty</th><th>Description</th><th class="num">Size</th></tr></thead>
<tbody>
{chr(10).join(rows)}
</tbody>
</table>
<p class="note">Qty is the number of prints for the configuration described in the notes;
“–” marks optional or reference-only files.</p>
</section>
<article class="notes" lang="{escape(design.lang)}">
<h2 lang="en">Design notes</h2>
{readme_html}
</article>"""
    return layout(design.title, body, depth=1, head=head, description=design.summary)


def extra_page(design: Design, doc: str, title: str, html: str) -> str:
    depth = 1 + doc.count("/")
    up = "../" * depth
    body = f"""<nav class="crumbs"><a href="{up}index.html">{escape(SITE_TITLE)}</a> /
<a href="{up}{escape(design.slug)}/index.html">{escape(design.title)}</a> /</nav>
<article class="notes" lang="{escape(design.lang)}">
{html}
</article>"""
    return layout(title, body, depth=depth, description=design.summary)


# Build -----------------------------------------------------------------------

def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def build(out: Path, root: Path = ROOT) -> list[Design]:
    designs = load_designs(root)
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)
    shutil.copytree(SITE_SOURCE / "assets", out / "assets")
    shutil.copytree(SITE_SOURCE / "vendor/three", out / "assets/vendor/three")

    for design in designs:
        published = {design.cover, *(part.file for part in design.parts)}
        pages = frozenset(design.pages)
        for doc in ("README.md", *design.pages):
            text = (root / design.slug / doc).read_text(encoding="utf-8")
            context = LinkContext(root, design.slug, doc, pages, published)
            is_readme = doc == "README.md"
            html = render_markdown(text, context, drop_title=is_readme)
            target = out / design.slug / output_name(doc)
            if is_readme:
                write(target, design_page(design, html, root))
            else:
                title = markdown_title(text, PurePosixPath(doc).stem)
                write(target, extra_page(design, doc, title, html))
        for name in sorted(published):
            target = out / design.slug / name
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(root / design.slug / name, target)

    write(out / "index.html", index_page(designs))
    return designs


# Checks ----------------------------------------------------------------------

class LinkCollector(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.urls: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        for name, value in attrs:
            if name in ("href", "src") and value:
                self.urls.append(value)


def broken_links(out: Path) -> list[str]:
    """Return relative links in the built HTML whose targets do not exist."""
    problems = []
    for page in sorted(out.rglob("*.html")):
        collector = LinkCollector()
        collector.feed(page.read_text(encoding="utf-8"))
        for url in collector.urls:
            if not is_relative_url(url):
                continue
            target = (page.parent / urlsplit(url).path).resolve()
            if not target.is_file():
                problems.append(f"{page.relative_to(out)}: {url}")
    return problems


def readme_table(designs: list[Design]) -> str:
    lines = [README_START,
             "| Design | Files | Notes |",
             "| --- | --- | --- |"]
    for design in designs:
        notes = design.summary.removesuffix(".")
        if design.prototype:
            notes += "; prototype"
        prints = plural(design.printed_parts, "print")
        files = f"{design.printed_files} STL ({prints}), {design.source} source"
        lines.append(f"| [{design.title}]({design.slug}/README.md) | {files} | {notes} |")
    lines.append(README_END)
    return "\n".join(lines)


def replace_readme_table(text: str, table: str) -> str:
    start, end = text.find(README_START), text.find(README_END)
    if start < 0 or end < start:
        raise SiteError("README.md: design table markers not found")
    return text[:start] + table + text[end + len(README_END):]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="output directory")
    parser.add_argument("--check", action="store_true",
                        help="verify links, the README table and the vendored files")
    parser.add_argument("--write-readme", action="store_true",
                        help="rewrite the design table in README.md")
    args = parser.parse_args()

    try:
        designs = build(args.out.resolve())
        readme_path = ROOT / "README.md"
        readme = readme_path.read_text(encoding="utf-8")
        updated = replace_readme_table(readme, readme_table(designs))
    except SiteError as error:
        raise SystemExit(str(error)) from error
    if args.write_readme and updated != readme:
        readme_path.write_text(updated, encoding="utf-8")
        readme = updated
    print(f"Built {len(designs)} designs into {args.out}")

    if args.check:
        problems = broken_links(args.out.resolve())
        problems += vendor_three.check(vendor_three.load_manifest())
        if updated != readme:
            problems.append("README.md design table is out of date; run with --write-readme")
        for problem in problems:
            print(problem, file=sys.stderr)
        if problems:
            raise SystemExit(1)
        print("Site check passed")


if __name__ == "__main__":
    main()
